### PR TITLE
close channel

### LINKED ISSUE #1: Use pointer to the WaitGroup to avoid deadlocks
Hi,
~~you have to use a pointer to the WaitGroup instead a copy to avoid deadlocks.
This is relevant for the examples and tests.~~

This is wrong. It's not the waitGroup but I get a deadlock after executing this example serveral times. It looks like a deadlock in your lib.

Go: go1.9.3 windows/amd64
OS: Windows 10

code
```go
package main

import (
	"sync"
	"time"

	"github.com/starptech/broadcast"
)

func main() {
	var s sync.WaitGroup
	b := make(broadcast.Broadcast)
	s.Add(10)
	for i := 0; i < 10; i++ {
		go func() {
			b.Receive()
			time.Sleep(1 * time.Millisecond)
			s.Done()
		}()
	}
	b <- 1
	s.Wait()
}

```
Trace
```
fatal error: all goroutines are asleep - deadlock!

goroutine 1 [semacquire]:
sync.runtime_Semacquire(0xc04201203c)
        C:/Go/src/runtime/sema.go:56 +0x40
sync.(*WaitGroup).Wait(0xc042012030)
        C:/Go/src/sync/waitgroup.go:131 +0x79
main.main()
        E:/go/work/src/github.com/starptech/broadcast/examples/simple.go:22 +0xfd

goroutine 10 [chan receive]:
github.com/starptech/broadcast.Broadcast.Receive(0xc0420101e0, 0x0, 0x0)
        E:/go/work/src/github.com/starptech/broadcast/broadcast.go:24 +0x8d
main.main.func1(0xc0420101e0, 0xc042012030)
        E:/go/work/src/github.com/starptech/broadcast/examples/simple.go:16 +0x32
created by main.main
        E:/go/work/src/github.com/starptech/broadcast/examples/simple.go:15 +0xb1

goroutine 11 [chan receive]:
github.com/starptech/broadcast.Broadcast.Receive(0xc0420101e0, 0x0, 0x0)
        E:/go/work/src/github.com/starptech/broadcast/broadcast.go:24 +0x8d
main.main.func1(0xc0420101e0, 0xc042012030)
        E:/go/work/src/github.com/starptech/broadcast/examples/simple.go:16 +0x32
created by main.main
        E:/go/work/src/github.com/starptech/broadcast/examples/simple.go:15 +0xb1

goroutine 12 [chan receive]:
github.com/starptech/broadcast.Broadcast.Receive(0xc0420101e0, 0x0, 0x0)
        E:/go/work/src/github.com/starptech/broadcast/broadcast.go:24 +0x8d
main.main.func1(0xc0420101e0, 0xc042012030)
        E:/go/work/src/github.com/starptech/broadcast/examples/simple.go:16 +0x32
created by main.main
        E:/go/work/src/github.com/starptech/broadcast/examples/simple.go:15 +0xb1

goroutine 13 [chan receive]:
github.com/starptech/broadcast.Broadcast.Receive(0xc0420101e0, 0x0, 0x0)
        E:/go/work/src/github.com/starptech/broadcast/broadcast.go:24 +0x8d
main.main.func1(0xc0420101e0, 0xc042012030)
        E:/go/work/src/github.com/starptech/broadcast/examples/simple.go:16 +0x32
created by main.main
        E:/go/work/src/github.com/starptech/broadcast/examples/simple.go:15 +0xb1
exit status 2
```

### PR DESCRIPTION
**Pull request by StarpTech**
Fix #1

### CODE REVIEW

**Comment by ericpauley** [comment]
Looks good, thanks! In reality these deadlocks are likely because, in some cases, 1ms isn't long enough for all channels to wait. Using broadcast channels like in the tests have a few problems for actual current use, unfortunately. Given that this library isn't really production-ready anyway, I'm going to merge.

**Comment by StarpTech** [comment]
It would be great to write this down explicitly in the Readme. As a user you gained the impression that this lib is ready to use. (also because of your article about it https://pauley.me/golang/2017/04/04/broadcast-channels-in-go.html)

**Comment by ericpauley** [comment]
It would be useful to update the readme to indicate exactly the limitations of broadcast channels in general. While this implementation works quite well, broadcast channels don't have many good applications, namely because there's no support for atomic unlock/wait operations. We can see the effects of this in the test, where it's impossible to be 100% sure when all goroutines have waited. The quintessential primitive for this is the condition variable.

For the use case of broadcast channels notifying anyone who happens to be listening with no specific guarantee on atomicity of listening, this library works great, and I've personally used it in high-availability projects, including software for communicating with satellites.

That being said, I'll work on adding a blurb to the readme informing users exactly what broadcast channels are useful for, and more importantly what they're not useful for.

**Comment by StarpTech** [comment]
This sounds good and reasonable :+1:

**Comment by StarpTech** [comment]
What did you do in that specific case when the go routines wasn't ready before the first completes? Or it never happened? I think to document this constraint would clarify a lot.

But I'm fine und understand it, thanks.

**Pull request merged**
